alg_name: "LoRA"
model_name: "xxx/Llama-3.1-8B-Instruct"
device: 0

lora_type: "adalora"
layers: []
num_steps: 40
batch_size: 1
max_length: 50
lr: 5e-3
weight_decay: 0
kl_factor: 0
rank: 8
lora_alpha: 32
lora_dropout: 0.1
norm_constraint: false
target_modules: ["q_proj", "v_proj"]  
model_parallel: false